### ISSUE TITLE
`cargo test` error

### ISSUE THREAD

**Issue by jeehoonkang** [nikomatsakis/rayon#413]
I tested with the latest master: 0b58f94262cbae63b95092eab655daaea9ec0d89

```
$ rustc --version
rustc 1.22.0-nightly (2f1ef9ef1 2017-09-05)


$ cargo test

running 150 tests
test iter::collect::test::left_produces_fewer_items ... ok
test iter::collect::test::left_produces_items_with_no_complete ... ok
test iter::collect::test::produce_fewer_items ... ok
test iter::collect::test::left_produces_too_many_items ... ok
test iter::collect::test::produce_too_many_items ... ok
test iter::collect::test::produces_items_with_no_complete ... ok
test iter::collect::test::right_produces_fewer_items ... ok
test iter::collect::test::right_produces_items_with_no_complete ... ok
test iter::collect::test::right_produces_too_many_items ... ok
test iter::find_first_last::test::find_first_folder_does_not_clobber_first_found ... ok
test iter::find_first_last::test::find_last_folder_yields_last_match ... ok
test iter::find_first_last::test::same_range_first_consumers_return_correct_answer ... ok
test iter::find_first_last::test::same_range_last_consumers_return_correct_answer ... ok
test iter::find_first_last::test::find_first_octillion ... ok
test iter::test::check_binary_heap ... ok
test iter::test::check_btree_map ... ok
test iter::test::check_btree_set ... ok
test iter::test::check_chunks ... ok
test iter::test::check_chunks_mut ... ok
test iter::test::check_chain ... ok
test iter::test::check_cmp_gt_direct ... ok
test iter::test::check_cmp_gt_to_seq ... ok
test iter::test::check_cmp_lt_direct ... ok
test iter::test::check_cmp_lt_to_seq ... ok
test iter::test::check_cmp_direct ... ok
test iter::test::check_cmp_short_circuit ... ok
test iter::test::check_cmp_lengths ... ok
test iter::test::check_cmp_to_seq ... ok
test iter::test::check_drops ... ok
test iter::test::check_count ... ok
test iter::test::check_either ... ok
test iter::test::check_empty_flat_map_sum ... ok
test iter::test::check_either_extend ... ok
test iter::test::check_enumerate ... ok
test iter::test::check_eq_direct ... ok
test iter::test::check_eq_to_seq ... ok
test iter::test::check_extend_heap ... ok
test iter::test::check_extend_pairs ... ok
test iter::test::check_find_is_present ... ok
test iter::test::check_find_not_present ... ok
test iter::test::check_flat_map_nested_ranges ... ok
test iter::test::check_extend_items ... ok
test iter::test::check_flatten_vec_empty ... ok
test iter::test::check_flatten_vec ... ok
test iter::test::check_for_each_with ... ok
test iter::test::check_fold_with ... ok
test iter::test::check_ge_equal_direct ... ok
test iter::test::check_ge_greater_direct ... ok
test iter::test::check_ge_equal_to_seq ... ok
test iter::test::check_ge_greater_to_seq ... ok
test iter::test::check_gt_direct ... ok
test iter::test::check_gt_to_seq ... ok
test iter::test::check_hash_set ... ok
test iter::test::check_hash_map ... ok
test iter::test::check_increment ... ok
test iter::test::check_indices_after_enumerate_split ... ok
test iter::test::check_inspect ... ok
test iter::test::check_le_equal_direct ... ok
test iter::test::check_le_less_direct ... ok
test iter::test::check_le_equal_to_seq ... ok
test iter::test::check_le_less_to_seq ... ok
test iter::test::check_linked_list ... ok
test iter::test::check_lt_direct ... ok
test iter::test::check_lt_to_seq ... ok
test iter::test::check_map_indexed ... ok
test iter::test::check_map_with ... ok
test iter::test::check_move ... ok
test iter::test::check_ne_direct ... ok
test iter::test::check_ne_lengths ... ok
test iter::test::check_ne_to_seq ... ok
test iter::test::check_options ... ok
test iter::test::check_partial_cmp_direct ... ok
test iter::test::check_partial_cmp_gt_direct ... ok
test iter::test::check_partial_cmp_gt_to_seq ... ok
test iter::test::check_partial_cmp_late_nan_direct ... ok
test iter::test::check_partial_cmp_late_nane_to_seq ... ok
test iter::test::check_partial_cmp_lt_direct ... ok
test iter::test::check_partial_cmp_lt_to_seq ... ok
test iter::test::check_partial_cmp_nan_short_circuit ... ok
test iter::test::check_partial_cmp_none_direct ... ok
test iter::test::check_partial_cmp_none_to_seq ... ok
test iter::test::check_cmp_rng_to_seq ... ok
test iter::test::check_partial_cmp_short_circuit ... ok
test iter::test::check_partial_cmp_to_seq ... ok
test iter::test::check_partition ... ok
test iter::test::check_partition_map ... ok
test iter::test::check_range_indexed ... ok
test iter::test::check_results ... ok
test iter::test::check_rev ... ok
test iter::test::check_skip ... ok
test iter::test::check_slice_indexed ... ok
test iter::test::check_slice_mut_indexed ... ok
test iter::test::check_partial_cmp_rng_to_seq ... ok
test iter::test::check_slice_split ... ok
test iter::test::check_split ... ok
test iter::test::check_sum_filtered_ints ... ok
test iter::test::check_sum_filtermap_ints ... ok
test iter::test::check_take ... ok
test iter::test::check_unzip ... ok
test iter::test::check_unzip_into ... ok
test iter::test::check_vec_deque ... ok
test iter::test::check_vec_indexed ... ok
test iter::test::check_while_some ... ok
test iter::test::check_windows ... ok
test iter::test::check_zip ... ok
test iter::test::check_zip_into_mut_par_iter ... ok
test iter::test::check_zip_into_par_iter ... ok
test iter::test::check_zip_range ... ok
test iter::test::execute ... ok
test iter::test::execute_cloned ... ok
test iter::test::execute_range ... ok
test iter::test::execute_strings ... ok
test iter::test::check_slice_split_mut ... ok
test iter::test::execute_unindexed_range ... ok
test iter::test::find_any ... ok
test iter::test::find_first_or_last ... ok
test iter::test::fold_is_full ... ok
test iter::test::fold_map_reduce ... ok
test iter::test::map_reduce ... ok
test iter::test::map_reduce_with ... ok
test iter::test::map_sum ... ok
test iter::test::execute_strings_split ... ok
test iter::test::min_max ... ok
test iter::test::min_max_by ... ok
test iter::test::par_iter_collect ... ok
test iter::test::par_iter_collect_binaryheap ... ok
test iter::test::par_iter_collect_btreemap ... ok
test iter::test::par_iter_collect_btreeset ... ok
test iter::test::par_iter_collect_cows ... ok
test iter::test::par_iter_collect_hashmap ... ok
test iter::test::par_iter_collect_hashset ... ok
test iter::test::par_iter_collect_linked_list ... ok
test iter::test::par_iter_collect_linked_list_flat_map_filter ... ok
test iter::test::par_iter_collect_option ... ok
test iter::test::par_iter_collect_result ... ok
test iter::test::par_iter_collect_vecdeque ... ok
test iter::test::par_iter_unindexed_flat_map ... ok
test iter::test::scope_mix ... ok
test range::check_range_split_at_overflow ... ok
test slice::mergesort::tests::test_split_for_merge ... ok
test slice::quicksort::tests::test_heapsort ... ok
test iter::test::check_lengths ... ok
test iter::test::min_max_by_key ... ok
test slice::test::test_par_sort ... ok

running 12 tests
test [compile-fail] compile-fail/cell_par_iter.rs ... ok
test [compile-fail] compile-fail/cannot_zip_filtered_data.rs ... ok
test [compile-fail] compile-fail/cannot_collect_filtermap_data.rs ... ok
test [compile-fail] compile-fail/must_use.rs ... ok
test [compile-fail] compile-fail/quicksort_race1.rs ... FAILED
test [compile-fail] compile-fail/no_send_par_iter.rs ... FAILED
test [compile-fail] compile-fail/quicksort_race3.rs ... FAILED
test [compile-fail] compile-fail/rc_return.rs ... ok
test [compile-fail] compile-fail/rc_upvar.rs ... ok
test [compile-fail] compile-fail/quicksort_race2.rs ... FAILED
test [compile-fail] compile-fail/scope_join_bad.rs ... ok
test [compile-fail] compile-fail/rc_par_iter.rs ... ok

failures:

---- [compile-fail] compile-fail/quicksort_race1.rs stdout ----
	
error: tests/compile-fail/quicksort_race1.rs:9: unexpected "warning": '9:14: 9:16: unused variable: `hi`'

error: 1 unexpected errors found, 0 expected errors not found
status: exit code: 101
command: rustc tests/compile-fail/quicksort_race1.rs -L /var/folders/7x/sbz6nj_x6jq91gk897n9wtk40000gn/T/ --target=x86_64-apple-darwin --error-format json -L /var/folders/7x/sbz6nj_x6jq91gk897n9wtk40000gn/T/quicksort_race1.stage-id.compile-fail.libaux -C prefer-dynamic -o /var/folders/7x/sbz6nj_x6jq91gk897n9wtk40000gn/T/quicksort_race1.stage-id -L target/debug/ -L target/debug/deps/
unexpected errors (from JSON output): [
    Error {
        line_num: 9,
        kind: Some(
            Warning
        ),
        msg: "9:14: 9:16: unused variable: `hi`"
    }
]

thread '[compile-fail] compile-fail/quicksort_race1.rs' panicked at 'explicit panic', /Users/jeehoon/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.2.10/src/runtest.rs:1097:12

---- [compile-fail] compile-fail/no_send_par_iter.rs stdout ----
	
error: tests/compile-fail/no_send_par_iter.rs:18: unexpected "error": '18:10: 18:15: no method named `count` found for type `rayon::iter::Map<rayon::option::Iter<'_, NoSend>, [closure@tests/compile-fail/no_send_par_iter.rs:17:14: 17:20]>` in the current scope [E0599]'

error: tests/compile-fail/no_send_par_iter.rs:22: unexpected "error": '22:10: 22:15: no method named `count` found for type `rayon::iter::FilterMap<rayon::option::Iter<'_, NoSend>, [closure@tests/compile-fail/no_send_par_iter.rs:21:21: 21:33]>` in the current scope [E0599]'

error: tests/compile-fail/no_send_par_iter.rs:26: unexpected "error": '26:10: 26:15: no method named `count` found for type `rayon::iter::Cloned<rayon::option::Iter<'_, NoSend>>` in the current scope [E0599]'

error: tests/compile-fail/no_send_par_iter.rs:18: expected error not found: Send` is not satisfied

error: tests/compile-fail/no_send_par_iter.rs:22: expected error not found: Send` is not satisfied

error: tests/compile-fail/no_send_par_iter.rs:26: expected error not found: Send` is not satisfied

error: 3 unexpected errors found, 3 expected errors not found
status: exit code: 101
command: rustc tests/compile-fail/no_send_par_iter.rs -L /var/folders/7x/sbz6nj_x6jq91gk897n9wtk40000gn/T/ --target=x86_64-apple-darwin --error-format json -L /var/folders/7x/sbz6nj_x6jq91gk897n9wtk40000gn/T/no_send_par_iter.stage-id.compile-fail.libaux -C prefer-dynamic -o /var/folders/7x/sbz6nj_x6jq91gk897n9wtk40000gn/T/no_send_par_iter.stage-id -L target/debug/ -L target/debug/deps/
unexpected errors (from JSON output): [
    Error {
        line_num: 18,
        kind: Some(
            Error
        ),
        msg: "18:10: 18:15: no method named `count` found for type `rayon::iter::Map<rayon::option::Iter<\'_, NoSend>, [closure@tests/compile-fail/no_send_par_iter.rs:17:14: 17:20]>` in the current scope [E0599]"
    },
    Error {
        line_num: 22,
        kind: Some(
            Error
        ),
        msg: "22:10: 22:15: no method named `count` found for type `rayon::iter::FilterMap<rayon::option::Iter<\'_, NoSend>, [closure@tests/compile-fail/no_send_par_iter.rs:21:21: 21:33]>` in the current scope [E0599]"
    },
    Error {
        line_num: 26,
        kind: Some(
            Error
        ),
        msg: "26:10: 26:15: no method named `count` found for type `rayon::iter::Cloned<rayon::option::Iter<\'_, NoSend>>` in the current scope [E0599]"
    }
]

not found errors (from test file): [
    Error {
        line_num: 18,
        kind: Some(
            Error
        ),
        msg: "Send` is not satisfied"
    },
    Error {
        line_num: 22,
        kind: Some(
            Error
        ),
        msg: "Send` is not satisfied"
    },
    Error {
        line_num: 26,
        kind: Some(
            Error
        ),
        msg: "Send` is not satisfied"
    }
]

thread '[compile-fail] compile-fail/no_send_par_iter.rs' panicked at 'explicit panic', /Users/jeehoon/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.2.10/src/runtest.rs:1097:12

---- [compile-fail] compile-fail/quicksort_race3.rs stdout ----
	
error: tests/compile-fail/quicksort_race3.rs:9: unexpected "warning": '9:10: 9:12: unused variable: `lo`'

error: 1 unexpected errors found, 0 expected errors not found
status: exit code: 101
command: rustc tests/compile-fail/quicksort_race3.rs -L /var/folders/7x/sbz6nj_x6jq91gk897n9wtk40000gn/T/ --target=x86_64-apple-darwin --error-format json -L /var/folders/7x/sbz6nj_x6jq91gk897n9wtk40000gn/T/quicksort_race3.stage-id.compile-fail.libaux -C prefer-dynamic -o /var/folders/7x/sbz6nj_x6jq91gk897n9wtk40000gn/T/quicksort_race3.stage-id -L target/debug/ -L target/debug/deps/
unexpected errors (from JSON output): [
    Error {
        line_num: 9,
        kind: Some(
            Warning
        ),
        msg: "9:10: 9:12: unused variable: `lo`"
    }
]

thread '[compile-fail] compile-fail/quicksort_race3.rs' panicked at 'explicit panic', /Users/jeehoon/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.2.10/src/runtest.rs:1097:12

---- [compile-fail] compile-fail/quicksort_race2.rs stdout ----
	
error: tests/compile-fail/quicksort_race2.rs:9: unexpected "warning": '9:14: 9:16: unused variable: `hi`'

error: 1 unexpected errors found, 0 expected errors not found
status: exit code: 101
command: rustc tests/compile-fail/quicksort_race2.rs -L /var/folders/7x/sbz6nj_x6jq91gk897n9wtk40000gn/T/ --target=x86_64-apple-darwin --error-format json -L /var/folders/7x/sbz6nj_x6jq91gk897n9wtk40000gn/T/quicksort_race2.stage-id.compile-fail.libaux -C prefer-dynamic -o /var/folders/7x/sbz6nj_x6jq91gk897n9wtk40000gn/T/quicksort_race2.stage-id -L target/debug/ -L target/debug/deps/
unexpected errors (from JSON output): [
    Error {
        line_num: 9,
        kind: Some(
            Warning
        ),
        msg: "9:14: 9:16: unused variable: `hi`"
    }
]

thread '[compile-fail] compile-fail/quicksort_race2.rs' panicked at 'explicit panic', /Users/jeehoon/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.2.10/src/runtest.rs:1097:12


failures:
    [compile-fail] compile-fail/no_send_par_iter.rs
    [compile-fail] compile-fail/quicksort_race1.rs
    [compile-fail] compile-fail/quicksort_race2.rs
    [compile-fail] compile-fail/quicksort_race3.rs

test result: FAILED. 8 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out

test test::negative_tests_compile_fail ... FAILED

running 2 tests
test [run-fail] run-fail/simple_panic.rs ... ok
test [run-fail] run-fail/iter_panic.rs ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

test test::negative_tests_run_fail ... ok

running 6 tests
test [run-pass] run-pass/init_zero_threads.rs ... ok
test [run-pass] run-pass/double_init_fail.rs ... ok
test slice::test::test_par_sort_unstable ... ok
test [run-pass] run-pass/stack_overflow_crash.rs ... ok
test [run-pass] run-pass/scope_join.rs ... ok
test [run-pass] run-pass/named-threads.rs ... ok
test slice::test::test_par_sort_stability ... ok
test iter::find_first_last::test::find_last_octillion has been running for over 60 seconds
test [run-pass] run-pass/sort-panic-safe.rs ... ok

test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

test test::positive_test_run_pass ... ok
test iter::find_first_last::test::find_last_octillion ... ok

failures:

---- test::negative_tests_compile_fail stdout ----
	thread 'test::negative_tests_compile_fail' panicked at 'Some tests failed', /Users/jeehoon/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.2.10/src/lib.rs:88:21


failures:
    test::negative_tests_compile_fail

test result: FAILED. 149 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by cuviper** [comment]
Should be fixed by #436, commits cherry-picked from @dns2utf8.
